---

- name: Install python if necessary
  raw: >
    test -x /usr/bin/python ||
    (test -x /usr/bin/apt-get && (apt-get update && apt-get -y install python) ||
    (test -x /usr/bin/yum && yum -y install python || exit 1))
  changed_when: False
